export type UiLocale = "ar" | "en";

export const copy = {
  en: {
    product: "Agentic Legal Copilot",
    variant: "D1T1 · Contract review · AR + EN",
    toggle: "العربية",
    intro:
      "Select a contract, run the three-agent review, and release the memo only after Counsel approval.",
    runReview: "Run review",
    running: "Running…",
    cancel: "Cancel",
    selectContract: "Contract",
    upload: "Upload text file",
    corpus: "Synthetic corpus",
    uploaded: "Uploaded",
    highRisk: "High-risk specimen",
    original: "Source text",
    clauses: "Clause breakdown",
    noContract: "Select a contract or upload a .txt / .md file.",
    stepper: "Live pipeline",
    extract: "Clause Extractor",
    risk: "Risk Assessor",
    memo: "Memo Drafter",
    gate: "Counsel gate",
    idle: "Idle",
    active: "In progress",
    done: "Done",
    waiting: "Awaiting approval",
    risks: "Risks and redlines",
    omission: "Silent omission",
    omissionHint: "A mandatory family is missing from this contract.",
    citations: "Citations",
    noCitations: "Citations appear after retrieval and drafting.",
    trace: "Run trace",
    traceHint: "Token usage, latency, and tool calls",
    tokens: "Tokens",
    tools: "Tool calls",
    latency: "Step latency",
    memoTitle: "Draft memo",
    approve: "Approve",
    reject: "Reject",
    editApprove: "Edit and approve",
    rejectReason: "Rejection comments",
    editBody: "Edited memo",
    counselId: "Counsel id",
    rag: "Ask the corpus",
    ragHint: "Direct RAG with structured citations. Empty corpus hits are refused.",
    ask: "Ask",
    refused: "Not enough information in the retrieved chunks.",
    healthOk: "API connected",
    healthFail: "API unreachable",
    awaitingHelp: "The memo is held at the Counsel gate. Approve, reject, or edit before release.",
    completed: "Review completed",
    rejected: "Rejected",
    failed: "Run failed",
    severity: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    category: {
      liability: "Liability",
      indemnity: "Indemnity",
      ip: "IP",
      payment: "Payment",
      termination: "Termination",
      jurisdiction: "Governing law",
      confidentiality: "Confidentiality",
      other: "Other",
    },
  },
  ar: {
    product: "المساعد القانوني الوكيلي",
    variant: "D1T1 · مراجعة العقود · عربي + إنجليزي",
    toggle: "English",
    intro: "اختر عقداً، شغّل المراجعة ثلاثية الوكلاء، ولا تُصدر المذكرة إلا بعد موافقة المستشار.",
    runReview: "تشغيل المراجعة",
    running: "جاري التشغيل…",
    cancel: "إلغاء",
    selectContract: "العقد",
    upload: "رفع ملف نصي",
    corpus: "المدونة الاصطناعية",
    uploaded: "مرفوع",
    highRisk: "عيّنة عالية المخاطر",
    original: "النص الأصلي",
    clauses: "تفكيك البنود",
    noContract: "اختر عقداً أو ارفع ملفاً ‎.txt / ‎.md.",
    stepper: "خط الأنابيب الحي",
    extract: "مستخرج البنود",
    risk: "مقيّم المخاطر",
    memo: "صائغ المذكرة",
    gate: "بوابة المستشار",
    idle: "خامل",
    active: "قيد التنفيذ",
    done: "تم",
    waiting: "بانتظار الموافقة",
    risks: "المخاطر والتعديلات",
    omission: "سهو صامت",
    omissionHint: "عائلة إلزامية غائبة عن هذا العقد.",
    citations: "الاستشهادات",
    noCitations: "تظهر الاستشهادات بعد الاسترجاع والصياغة.",
    trace: "أثر التشغيل",
    traceHint: "استهلاك الرموز وزمن التنفيذ واستدعاءات الأدوات",
    tokens: "الرموز",
    tools: "استدعاءات الأدوات",
    latency: "زمن الخطوة",
    memoTitle: "مسودة المذكرة",
    approve: "موافقة",
    reject: "رفض",
    editApprove: "تعديل ثم موافقة",
    rejectReason: "ملاحظات الرفض",
    editBody: "المذكرة المعدّلة",
    counselId: "معرّف المستشار",
    rag: "اسأل المدونة",
    ragHint: "استرجاع مباشر مع استشهادات منظمة. يُرفض الجواب إن لم تكفِ المقاطع.",
    ask: "اسأل",
    refused: "لا توجد معلومات كافية في المقاطع المسترجعة.",
    healthOk: "واجهة البرمجة متصلة",
    healthFail: "واجهة البرمجة غير متاحة",
    awaitingHelp: "المذكرة موقوفة عند بوابة المستشار. وافق أو ارفض أو عدّل قبل الإصدار.",
    completed: "اكتملت المراجعة",
    rejected: "مرفوضة",
    failed: "فشل التشغيل",
    severity: {
      critical: "حرج",
      high: "عالٍ",
      medium: "متوسط",
      low: "منخفض",
    },
    category: {
      liability: "المسؤولية",
      indemnity: "التعويض",
      ip: "الملكية الفكرية",
      payment: "الدفع",
      termination: "الإنهاء",
      jurisdiction: "القانون الحاكم",
      confidentiality: "السرية",
      other: "أخرى",
    },
  },
} as const;
