export type UiLocale = "ar" | "en";

export const copy = {
  en: {
    product: "Legal Copilot D1T1",
    productAr: "المساعد القانوني الذكي",
    variant: "D1T1 · Contract review · AR + EN",
    toggle: "العربية",
    langEn: "English",
    langAr: "العربية",
    intro:
      "Select a contract, run the three-agent review, and release the memo only after Counsel approval.",
    runReview: "Run Review",
    running: "Running…",
    cancel: "Cancel",
    explorer: "Document explorer",
    pipeline: "Live agent pipeline",
    pipelineLive: "Live",
    analyzing: "Analyzing…",
    completedBadge: "Completed",
    awaitingCounsel: "Awaiting approval",
    extractOutput: "{n} clauses extracted",
    riskOutput: "{n} risks flagged",
    memoOutput: "Ready for review",
    gateOutput: "Legal decision required",
    gateDecided: "Counsel decision recorded",
    extractPending: "Waiting to extract",
    riskPending: "Waiting to assess",
    memoPending: "Waiting to draft",
    gatePending: "Human-in-the-loop",
    liveAgentStart: "Agent started",
    liveClause: "Clause extracted",
    liveRisk: "Risk flagged",
    liveAwaiting: "Held for Counsel",
    liveDecision: "Counsel decided",
    liveTool: "Tool call",
    counselDesk: "Counsel desk",
    selectContract: "Contract",
    upload: "Upload text file",
    corpus: "Synthetic corpus",
    uploaded: "Uploaded",
    highRisk: "High-risk specimen",
    original: "Source text",
    clauses: "Clause breakdown",
    noContract: "Select a contract or upload a .txt / .md file.",
    stepper: "Live pipeline",
    extract: "Clause Extractor",
    risk: "Risk Assessor",
    memo: "Memo Drafter",
    gate: "Counsel Approval Gate",
    idle: "Idle",
    active: "In progress",
    done: "Done",
    waiting: "Awaiting approval",
    risks: "Risks and redlines",
    omission: "Silent omission",
    omissionHint: "A mandatory family is missing from this contract.",
    citations: "Citations",
    noCitations: "Citations appear after retrieval and drafting.",
    trace: "Run trace",
    traceHint: "Token usage, latency, and tool calls",
    tokens: "Tokens",
    tools: "Tool calls",
    latency: "Step latency",
    memoTitle: "Draft memo",
    approve: "Approve",
    reject: "Reject",
    editApprove: "Edit and approve",
    rejectReason: "Rejection comments",
    editBody: "Edited memo",
    counselId: "Counsel id",
    rag: "RAG copilot",
    ragHint: "Grounded answers with numbered citations. Empty hits are refused.",
    ask: "Ask",
    ragCollapse: "Hide copilot",
    ragExpand: "Show copilot",
    runId: "Run",
    refused: "Not enough information in the retrieved chunks.",
    redlines: "Playbook redline",
    diffDel: "Contract (remove)",
    diffIns: "Playbook (add)",
    jumpToClause: "Show in contract",
    citationHint: "Click a citation to highlight its source clause.",
    exportMemo: "Export approved memo",
    printPdf: "Print / Save PDF",
    printTitle: "Counsel review memorandum",
    printDisclaimer: "Assistive draft. Not legal advice. Issued for Counsel review.",
    printSignature: "Legal Counsel signature",
    printDate: "Date",
    printStatus: "Status",
    printExported: "As of",
    copy: "Copy",
    copied: "Copied!",
    copyClause: "Copy clause",
    copyMemo: "Copy memo",
    copyPlaybook: "Copy playbook",
    expand: "Show more",
    collapse: "Show less",
    filterAll: "All",
    filterCritical: "Critical risks",
    filterMissing: "Missing clauses",
    noFilterMatches: "No clauses match this filter.",
    emptyRisks: "Risks appear after the assessor runs.",
    healthOk: "Backend Connected",
    healthFail: "Backend unreachable",
    awaitingHelp: "The memo is held at the Counsel gate. Approve, reject, or edit before release.",
    completed: "Review completed",
    rejected: "Rejected",
    failed: "Run failed",
    severity: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    category: {
      liability: "Liability",
      indemnity: "Indemnity",
      ip: "IP",
      payment: "Payment",
      termination: "Termination",
      jurisdiction: "Governing law",
      confidentiality: "Confidentiality",
      other: "Other",
    },
  },
  ar: {
    product: "Legal Copilot D1T1",
    productAr: "المساعد القانوني الذكي",
    variant: "D1T1 · مراجعة العقود · عربي + إنجليزي",
    toggle: "English",
    langEn: "English",
    langAr: "العربية",
    intro: "اختر عقداً، شغّل المراجعة ثلاثية الوكلاء، ولا تُصدر المذكرة إلا بعد موافقة المستشار.",
    runReview: "تشغيل المراجعة",
    running: "جاري التشغيل…",
    cancel: "إلغاء",
    explorer: "مستكشف المستند",
    pipeline: "خط أنابيب الوكلاء الحي",
    pipelineLive: "مباشر",
    analyzing: "جاري التحليل...",
    completedBadge: "تم الانتهاء",
    awaitingCounsel: "بانتظار الاعتماد",
    extractOutput: "{n} بند تم تفكيكه",
    riskOutput: "تم رصد {n} مخاطر",
    memoOutput: "جاهز للمراجعة",
    gateOutput: "مطلوب قرار قانوني",
    gateDecided: "تم تسجيل قرار المستشار",
    extractPending: "بانتظار الاستخراج",
    riskPending: "بانتظار التقييم",
    memoPending: "بانتظار الصياغة",
    gatePending: "قرار بشري مطلوب",
    liveAgentStart: "بدأ الوكيل",
    liveClause: "تم تفكيك بند",
    liveRisk: "رُصدت مخاطرة",
    liveAwaiting: "موقوف لدى المستشار",
    liveDecision: "صدر قرار المستشار",
    liveTool: "استدعاء أداة",
    counselDesk: "مكتب المستشار",
    selectContract: "العقد",
    upload: "رفع ملف نصي",
    corpus: "المدونة الاصطناعية",
    uploaded: "مرفوع",
    highRisk: "عيّنة عالية المخاطر",
    original: "النص الأصلي",
    clauses: "تفكيك البنود",
    noContract: "اختر عقداً أو ارفع ملفاً ‎.txt / ‎.md.",
    stepper: "خط الأنابيب الحي",
    extract: "مستخرج البنود",
    risk: "مقيّم المخاطر",
    memo: "صائغ المذكرة",
    gate: "بوابة المستشار",
    idle: "خامل",
    active: "قيد التنفيذ",
    done: "تم",
    waiting: "بانتظار الموافقة",
    risks: "المخاطر والتعديلات",
    omission: "سهو صامت",
    omissionHint: "عائلة إلزامية غائبة عن هذا العقد.",
    citations: "الاستشهادات",
    noCitations: "تظهر الاستشهادات بعد الاسترجاع والصياغة.",
    trace: "أثر التشغيل",
    traceHint: "استهلاك الرموز وزمن التنفيذ واستدعاءات الأدوات",
    tokens: "الرموز",
    tools: "استدعاءات الأدوات",
    latency: "زمن الخطوة",
    memoTitle: "مسودة المذكرة",
    approve: "موافقة",
    reject: "رفض",
    editApprove: "تعديل ثم موافقة",
    rejectReason: "ملاحظات الرفض",
    editBody: "المذكرة المعدّلة",
    counselId: "معرّف المستشار",
    rag: "مساعد الاسترجاع",
    ragHint: "إجابات مستندة إلى المقاطع مع استشهادات مرقمة. يُرفض الجواب إن لم تكفِ النتائج.",
    ask: "اسأل",
    ragCollapse: "إخفاء المساعد",
    ragExpand: "إظهار المساعد",
    runId: "التشغيل",
    refused: "لا توجد معلومات كافية في المقاطع المسترجعة.",
    redlines: "تعديل الدليل",
    diffDel: "العقد (حذف)",
    diffIns: "الدليل (إضافة)",
    jumpToClause: "إظهار البند",
    citationHint: "انقر الاستشهاد للانتقال إلى البند في العقد.",
    exportMemo: "تصدير المذكرة المعتمدة",
    printPdf: "طباعة / حفظ PDF",
    printTitle: "مذكرة مراجعة المستشار",
    printDisclaimer: "مسودة مساعدة. ليست استشارة قانونية. تصدر لمراجعة المستشار.",
    printSignature: "توقيع المستشار القانوني",
    printDate: "التاريخ",
    printStatus: "الحالة",
    printExported: "اعتباراً من",
    copy: "نسخ",
    copied: "تم النسخ!",
    copyClause: "نسخ البند",
    copyMemo: "نسخ المذكرة",
    copyPlaybook: "نسخ الدليل",
    expand: "عرض المزيد",
    collapse: "عرض أقل",
    filterAll: "الكل",
    filterCritical: "مخاطر حرجة",
    filterMissing: "بنود غائبة",
    noFilterMatches: "لا توجد بنود مطابقة لهذا التصفية.",
    emptyRisks: "تظهر المخاطر بعد تشغيل المقيّم.",
    healthOk: "الخلفية متصلة",
    healthFail: "الخلفية غير متاحة",
    awaitingHelp: "المذكرة موقوفة عند بوابة المستشار. وافق أو ارفض أو عدّل قبل الإصدار.",
    completed: "اكتملت المراجعة",
    rejected: "مرفوضة",
    failed: "فشل التشغيل",
    severity: {
      critical: "حرج",
      high: "عالٍ",
      medium: "متوسط",
      low: "منخفض",
    },
    category: {
      liability: "المسؤولية",
      indemnity: "التعويض",
      ip: "الملكية الفكرية",
      payment: "الدفع",
      termination: "الإنهاء",
      jurisdiction: "القانون الحاكم",
      confidentiality: "السرية",
      other: "أخرى",
    },
  },
} as const;
